# Generated by Django 5.0.6 on 2024-06-26 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('brand', models.CharField(default='Generic', max_length=200)),
                ('description', models.TextField(default='None')),
                ('primary_img', models.ImageField(default=None, upload_to='store/static/media/products')),
                ('second_img', models.ImageField(default=None, upload_to='store/static/media/products')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
        ),
    ]
